apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-practice-app-service-config
data:
  POSTGRES_USER: "kuber_practice_user"
  POSTGRES_HOST: "kuber-practice-app-postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kuber_practice"
  MIGRATIONS_DIRECTORY: "/app/db/migrations"
