apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-practice-app
  namespace: default
  labels:
    app: kuber-practice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuber-practice-app
  template:
    metadata:
      labels:
        app: kuber-practice-app
    spec:
      containers:
        - image: eu.gcr.io/my-new-project-467616/kuber_practice_app:latest
          name: kuber-practice-app
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthcheck
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kuber-practice-app-secrets
                  key: api_key
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: PORT
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: POSTGRES_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuber-practice-app-secrets
                  key: postgres_password
            - name: APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: POSTGRES_HOST
            - name: APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: POSTGRES_PORT
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: POSTGRES_DB
            - name: APP_DB_MIGRATIONS_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: MIGRATIONS_DIRECTORY
            - name: APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: kuber-practice-app-service-config
                  key: REDIS_HOST
            - name: APP_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kuber-practice-app-secrets
                  key: redis_password