apiVersion: v1
kind: Service
metadata:
  name: kuber-practice-app-service
  labels:
    app: kuber-practice-app
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kuber-practice-app
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kuber-practice-app-postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: kuber-practice-app-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: kuber-practice-app-redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    app: kuber-practice-app-redis